apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ukky
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-ukky@sha256:c0287c0f1dd2a94a2bca46939d652e407f6df85ccf51e288925fd6a45c8eaeef
        name: my-nodejs
        resources: {}
status: {}
